### ISSUE TITLE
Should we include roads marked as "Access" or "Gate"

### ISSUE THREAD

**Issue by CloCkWeRX** [q-bits/osm-scripts#4]
Examples:
- Rail Service Access - a dirt road next to railway lines that is not public accessible
- Access Road - In the middle of the airport
- Gate A - West lakes stadium

I haven't found too many that I would bother with naming in OSM or that I would expect to be signed, most are highway=service.

**Comment by q-bits** [comment]
Fixed in commit 5e33d5c
